#!/bin/bash 
#
### BEGIN INIT INFO
# dc_statusd
# chkconfig: 345 95 20
### END INIT INFO

DAEMON=$(basename ${0})
# figure out a better way to locate the script
SCRIPT=/opt/nofry/monitor_status
PIDFILE="/var/run/$DAEMON.pid"

# source function library
. /etc/rc.d/init.d/functions

# If the daemon is not there, then exit.
test -x $SCRIPT || exit 5

case $1 in
  start)
    printf "%-50s" "Starting $DAEMON..."
    PID=$($SCRIPT > /dev/null 2>&1 & echo $!)
    
    if [ -z "$PID" ]; then
    	printf "%s\n" "Fail"
    else
    	echo $PID > $PIDFILE
    	printf "%s\n" "Ok"
    fi
    ;;
  stop)
    # Stop the daemon.
    printf "%-50s" "Stopping $DAEMON"
    PID=`cat $PIDFILE`
    if [ -f $PIDFILE ]; then
    	kill -9 $PID
    	printf "%s\n" "Ok"
        logger "[${DAEMON}] stopping"
    	rm -f $PIDFILE
    else
    	printf "%s\n" "pidfile not found"
    fi
    ;;
  restart)
    echo "got restart"
    ;;
  reload)
    echo "got the message to reload"
    ;;
  status)
    printf "%-50s" "Checking $DAEMON..."
    if [ -f $PIDFILE ]; then
    	PID=`cat $PIDFILE`
    	if [ -z "`ps -elf | grep $PID | grep -v grep`" ]; then
    		printf "%s\n" "Process dead but pidfile exists"
    	else
    		echo "Running"
    	fi
    else
    	printf "%s\n" "Service not running"
    fi
    ;;
  *)
   # For invalid arguments, print the usage message.
   echo "Usage: $0 {start|stop|restart|reload|status}"
   exit 2
   ;;
esac
