#!/bin/bash 
# dc-tempd daemon
# chkconfig: 345 95 20
# description: watches ups power status and sets status

DAEMON=$(basename ${0})
SCRIPT=dc_tempd
SCRIPT_PATH=/opt/nofry
PIDFILE="/var/run/$DAEMON.pid"

# source function library
. /etc/rc.d/init.d/functions

case "$1" in
start)
	printf "%-50s" "Starting $DAEMON..."
	PID=`$SCRIPT_PATH/$SCRIPT > /dev/null 2>&1 & echo $!`

	if [ -z "$PID" ]; then
		printf "%s\n" "Fail"
	else
		echo $PID > $PIDFILE
		printf "%s\n" "Ok"
	fi
;;
status)
	printf "%-50s" "Checking $DAEMON..."
	if [ -f $PIDFILE ]; then
		PID=`cat $PIDFILE`
		if [ -z "`ps -elf | grep $PID | grep -v grep`" ]; then
			printf "%s\n" "Process dead but pidfile exists"
		else
			echo "Running"
		fi
	else
		printf "%s\n" "Service not running"
	fi
;;
stop)
	printf "%-50s" "Stopping $DAEMON"
	PID=`cat $PIDFILE`
	if [ -f $PIDFILE ]; then
		kill -9 $PID
		printf "%s\n" "Ok"
		rm -f $PIDFILE
	else
		printf "%s\n" "pidfile not found"
	fi
;;
*)
	echo "Usage: $0 {start|stop|status}"
	exit 1
esac
