#!/bin/bash

#######################################
# Monitor the ups room for high temperatures
#
# Globals:
#    SIGNAL_THRESHOLD
#    NC_THRESHOLD
# Arguments:
#    None
# Returns: 
#    None
#
# Short Description: Monitors the temperature levels in the UPS room, sends a 
#                    email/trap warnings when temperatures reach the
#                    SIGNAL_THRESHOLD and performs and Emergency Power 
#                    Off (EPO) when temps reach EPO_THRESHOLD.
#
#######################################

source $(dirname $0)/lib/killbot.conf
source $(dirname $0)/lib/misc_utilities.sh
source $(dirname $0)/lib/env_sensing_utilities.sh

logger "[`basename $0`] starting" 

#######################################
# the main loop- constantly checking to make sure that everything is OK

COUNTER=1      #TODO comment out

while [ $COUNTER -gt 0 ]; do
  HIGHTEMP=$(getMaxTemp_upsRoom ${UPS_ROOM} ${UPS_ROOM_COMMUNITY})

  #COUNTER=$((COUNTER - 1))

  if [ $HIGHTEMP -gt $SIGNAL_THRESHOLD ]; then
    logger "[WARNING] ($HIGHTEMP degrees) in the UPS room"

    # TODO set ups to bypass
  fi
done


COUNTER=1

while [ $COUNTER -gt 0 ]; do
  HIGHERTEMP=$(getMaxTemp_upsRoom ${UPS_ROOM} ${UPS_ROOM_COMMUNITY})

  logger "[`basename $0`] - continuing to watch temperature ($HIGHTEMP)"

  #COUNTER=$((COUNTER - 1))

  if [ $HIGHERTEMP -gt $EPO_THRESHOLD ]; then
    logger "[WARNING] ($HIGHERTEMP degrees) in the UPS room "

    # EPO ups1 #TODO
    # EPO ups2 #TODO
    break;
  fi
done

logger "[`basename $0`] finished running"
